"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var circleobj = new circle_1.Circle(2);
circleobj.Myarea();
circleobj.Display();
var rectObj = new rectangle_1.Rectangle(3, 4);
rectObj.Myarea();
rectObj.Display();
